### ISSUE TITLE
pa11y.js Throwing an error

### ISSUE THREAD

**Issue by mel-miller** [fourkitchens/emulsify-gulp#102]
I'm in the process of updating to emulsify-gulp 4.0.0. on my emulsify-cloned custom theme. Yarn start runs without error, but the first save I make after that kills the gulp task with the following error: 

```
[Browsersync] Serving files from: ./
[10:28:04] Starting 'css'...
/Users/miller.2676/dev/rc-osu/web/themes/wcm/wcm8_patterns/node_modules/emulsify-gulp/gulp-tasks/pa11y.js:68
      items.forEach((item) => {
            ^

TypeError: Cannot read property 'forEach' of undefined
    at fs.readdir (/Users/miller.2676/dev/rc-osu/web/themes/wcm/wcm8_patterns/node_modules/emulsify-gulp/gulp-tas
ks/pa11y.js:68:13)
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm going to continue to troubleshoot within my theme, but I wanted to see if you had any ideas, or if this is actually a bug.  Thanks!

**Comment by evanmwillhite** [comment]
@mel-miller this might be a bug actually. Can you describe the situation of what you were editing, particularly the directory you were in? I think I'll have to recreate it.

**Comment by mel-miller** [comment]
I was working in the _patterns directory. Whenever I save a component file (scss, yml, or twig) that would trigger the gulp watch task is when I get the error.

**Comment by evanmwillhite** [comment]
So you get this error while editing any file in any directory inside `_patterns`?

**Comment by mel-miller** [comment]
Yes, that is correct.

**Comment by mel-miller** [comment]
I haven't been able to recreate the issue on a brand-new emulsify clone theme. I'm going to continue to try and figure out what deviation on my original theme could be causing this. Please let me know if you have any ideas of where to begin. Thanks!

**Comment by evanmwillhite** [comment]
@mel-miller can you review that ☝️ within your cloned theme? I don't know that the accessibility test will run accurately, but at least this should stop it from the error.

**Comment by mel-miller** [comment]
Yes, you are correct. It did stop the error. Not sure if the test ran correctly though. Is there an obvious violation that I can try to be sure?

**Comment by indifisher** [comment]
I've just randomly run into this as well whilst editing the `_00-head.twig` file in `components/_meta`

```
File pattern-lab/source/_meta/_00-head.twig was changed, running tasks...
/Users/######/Sites/######/web/themes/custom/######/node_modules/emulsify-gulp/gulp-tasks/pa11y.js:68
      items.forEach((item) => {
            ^

TypeError: Cannot read property 'forEach' of undefined
    at fs.readdir (/Users/######/Sites/######/web/themes/custom/######/node_modules/emulsify-gulp/gulp-tasks/pa11y.js:68:13)
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! emulsify@1.0.0 start: `gulp compile && gulp theme`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the emulsify@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```


Not sure if that helps pin this down any further?

**Comment by evanmwillhite** [comment]
@indifisher I noticed that too - I think this above should fix it. Basically, when trying to run pa11y on that directory, `items` doesn't exist because it doesn't have a `.yml` file. I'm gonna see if I can get a review on that PR - thanks for the bump here.

Also @mel-miller sorry - I missed your question above. You should be able to quickly test by just changing a background/foreground color to be the same (like a button with black background and black text).
