### ISSUE TITLE
local.gulp-config.js

### ISSUE THREAD

**Issue by davidmoret** [fourkitchens/emulsify-gulp#29]
Hi,
I'm trying to change the gulp config but my local.gulp-config file is not considered. When I modify gulp-config.js in node_modules this works. I try to get a watch / refresh via browsersync as much on the pattern-lab side as on the drupal side, maybe there is a way provided by you to get this result? (Thanks for this theme)

**Comment by amazingrando** [comment]
@davidmoret I know that this response comes a few months after you posted this issue. Could you post your files so that we can see about replicating the issue? Thanks!

**Comment by evanmwillhite** [comment]
@davidmoret I just tested this using a fresh install of both emulsify and emulsify-gulp and was able to create a local config file and have it be read. The name for that file should be `local.gulp-config.js` if that helps. I'm going to close this, but if you are still having an issue, please do respond and we can reopen.

**Comment by danny-englander** [comment]
Hi, I know this is long after this issue was opened but I am running into the same issue as well. Should I open a new issue with a complete report of my setup or stay in this one?

**Comment by evanmwillhite** [comment]
@danny-englander we can keep it in here. Sorry for the issue - let us know as much about your setup as possible if you can. Thank you!

**Comment by evanmwillhite** [comment]
@danny-englander I've been there many times! So glad you spelled all this out in case anyone else runs into it. I'll close again, but feel free to reopen if you run into any issues.
