### ISSUE TITLE
Possible to update gulp-sass?

### ISSUE THREAD

**Issue by bryce-gilhome-cp** [fourkitchens/emulsify-gulp#41]
Hi, I'm using emulsify-gulp in a project running on an Alpine docker container - the issue is that Alpine support for node-sass was only introduced in node-sass:4.1.0, which means using gulp-sass:>=3.1.0.

I've set this dependency using npm shrinkwrap but was wondering if there was any chance of updating the dependency in emulsify-gulp?

**Comment by bryce-gilhome-cp** [comment]
Just noticed this is a dupe of https://github.com/fourkitchens/emulsify-gulp/issues/40

**Comment by amazingrando** [comment]
@bryce-gilhome-cp We are looking to update the dependencies in the next week or two. Thanks!
