### ISSUE TITLE
Use versioning

### ISSUE THREAD

**Issue by bradjones1** [fourkitchens/emulsify-gulp#50]
I'm not an Node/npm expert but I am running into a situation where yarn, at least, is not always installing/using the latest version of the package from the repository if its local copy is the same version, which has been pinned at 1.0.0 for a while. Could the version get a bump on a regular basis?

**Comment by amazingrando** [comment]
@bradjones1 We're starting to add releases and increment package numbers. If you pull the latest from Emulsify you'll find an updated yarn.lock that points to the most recent Emulsify Gulp.

While we iron out versioning details and schedule, you can use `yarn upgrade emulsify-gulp` to get the latest.
