### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/emulsify-gulp#52]
I propose that we put this on NPM under Four Kitchens. https://www.npmjs.com/org/fourkitchens

**Comment by rootwork** [comment]
That'd be nice since I assume then it would be more easily versionable -- it's been somewhat challenging to use, since it can change at any time with updates that can break older versions of emulsify. (That is, it works fine on new installs, but not being able to pin to a specific version means ongoing development with it can be tricky.)

**Comment by amazingrando** [comment]
@rootwork As of the end of last week, we have started to version Emulsify Gulp (and Emulsify). We're looking to smooth out our bumpy start. :-)

**Comment by EvanLovely** [comment]
This would be really helpful as I've been on a couple projects using Emulsify and both had times where `master` here got updated and it broke stuff for us after someone did a fresh install or a CI build. Also, may I recommend the use of [the command `npm version`](https://docs.npmjs.com/cli/version) - run `npm version minor` (you can pass in `major`, `minor`, or `patch`) and that will create a commit where it updates the value in `package.json` and tags the commit. Make sure you either run `git push && git push --tags` or just run `git config --global push.followTags true` to always push tags (what I do). So to deploy a new version it's as simple as:

```
npm version minor
git push && git push --tags
npm publish
```

**Comment by amazingrando** [comment]
@EvanLovely Thanks! We've started tagging releases so that breaking changes are less likely to happen.

**Comment by evanmwillhite** [comment]
Looks like this has been taken care of! https://www.npmjs.com/package/@fourkitchens/emulsify-gulp
