### ISSUE TITLE
patternlab root derived from config file

### ISSUE THREAD

**Issue by jasonlttl** [fourkitchens/emulsify-gulp#61]
I wanted to tweak some pattern-lab settings and so I've got a local.gulp-config.js with this in it.

```
    patternLab: {
      enabled: true,
      configFile: `${themeDir}/components/config.yml`,
      snip...
    },
```

It finds the custom config file, which is outside of the gitignored pattern-lab root, but then it crashes because emulsify-gulp calculates the pattern lab root using the path to the config file (which it expects to be inside the pattern-lab root at a particular depth).

```
const plRoot = path.join(config.patternLab.configFile, '../..');
const plSource = path.join(plRoot, plConfig.sourceDir);
const consolePath = path.join(plRoot, 'core/console');
```

Am I missing something? I was tempted to submit a merge request that adds a root param to the gulp config, but the assumption that the config file is always in the patternlab root makes me wonder if I'm trying to override configuration the wrong way.

PS. Thanks for the great work on emulsify.

**Comment by evanmwillhite** [comment]
Actually, that's a great idea for a PR. It's probably just that nobody has tried that, but it's a perfectly valid need. In fact, I'm pretty sure we could just use [the `config.paths.pattern_lab` variable](https://github.com/fourkitchens/emulsify-gulp/blob/master/gulp-config.js#L16), right? Something that is already set and can be overridden in config locally?

**Comment by jasonlttl** [comment]
Thank you enormously for the quick response. 

Using the existing variable seems like a great idea. I'll try to add a pull request in the next day or so (working on a crazy deadline so may take a bit).

**Comment by evanmwillhite** [comment]
I think line may need to be `const plRoot = path.join(config.paths.pattern_lab, '../');`

Not sure about using it elsewhere, but this works better in the default usage

**Comment by willthemoor** [comment]
> I think line may need to be const plRoot = path.join(config.paths.pattern_lab, '../');

That's what's in the PR I submitted. Not sure what's going with the Travis fail. If there's something I can do to fix it, please let me know.

**Comment by evanmwillhite** [comment]
Just merged, so this is good.
