### ISSUE TITLE
Unify scripts task between Pattern Lab and Drupal

### ISSUE THREAD

**Issue by infiniteluke** [fourkitchens/emulsify-gulp#65]
If Pattern Lab can take per component files, it would enable us to only need 1 build step for JS.

**Comment by evanmwillhite** [comment]
In doing some research, at the very least we can just do something like this in each component:

```
{% if pl_script == TRUE %}
  <script src="../../../../dist/02-molecules/accordion-item/accordion-item.js"></script>
{% endif %}
```
If that variable is true, that component will just print the script file that is created via the `scripts` gulp task. Then we wouldn't need the `styleguide-scripts` task at all. 

We could do this now and it would involve:
1. Removing [this line](https://github.com/fourkitchens/emulsify/blob/develop/components/_meta/_01-foot.twig#L15)
2. Remove [this task](https://github.com/fourkitchens/emulsify-gulp/blob/develop/index.js#L59-L72) and all references to it ([this](https://github.com/fourkitchens/emulsify-gulp/blob/develop/index.js#L115), [this](https://github.com/fourkitchens/emulsify-gulp/blob/develop/index.js#L137) and [this](https://github.com/fourkitchens/emulsify-gulp/blob/develop/index.js#L158)).

We can also do something else, like:
1. Add some sort of mechanism to automatically reference script files from the component directory.
2. We could also make this [Twig function](https://github.com/fourkitchens/emulsify/blob/develop/components/_twig-components/functions/pl_attach-library.function.php) attach the library. If we could use [identical syntax to Drupal's](https://github.com/fourkitchens/emulsify/blob/develop/templates/navigation/menu--main.html.twig#L21) that would work on both sides, that would be cool.

Either way, this allows us to get rid of this unnecessary gulp script!

**Comment by ModulesUnraveled** [comment]
I don't follow everything that's going on here, but this is true:
> we could use identical syntax to Drupal's

I'm 100% in favor!

If I understand correctly, you're proposing that we effectively make PL attach the js only when needed, just like Drupal 8 does AND it would only have to be written once to work in both places. If that's the case, YES PLEASE! :)

**Comment by evanmwillhite** [comment]
Ok, cool - that's kinda where my head was at. I'll take a stab at this and see if we can't make that happen.

**Comment by evanmwillhite** [comment]
This has been done in that merged PR above!
