### ISSUE TITLE
Gulp gh-pages-deploy script currently broken because of dependency

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify-gulp#70]
Just noting this in case anybody comes along and wonders...

Here's the [issue](https://github.com/shinnn/gulp-gh-pages/issues/116) and here's the [fix](https://github.com/shinnn/gulp-gh-pages/pull/117) we're waiting on.

**Comment by froboy** [comment]
@evanmwillhite I've gotten around this breaking by the method in this PR https://github.com/palantirnet/butler/pull/93/files. I did something similar in our emulsify at the root of the project, I'm not sure if you'd want to require patching in either of the projects, but here's how it works if you do...

- install https://www.npmjs.com/package/patch-package (making sure to both add the `prepare` script to `package.json` and install the package.
- grab the gift patch from here https://github.com/palantirnet/butler/blob/9977bd56faf0b45b57ce113a8e22c110ae7e59fb/patches/gift%2B0.6.1.patch
- (just the first time) run `yarn prepare` (it works with npm too, but requires a newish version).

Once that single line of `gift/lib/commit.js` gets commented out, you can deploy without any problem, and I haven't seen any downside to removing it.

**Comment by evanmwillhite** [comment]
Fixed in https://github.com/fourkitchens/emulsify-gulp/pull/74
