### ISSUE TITLE
Ensure build task is complete

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify-gulp#84]
Based on https://github.com/fourkitchens/emulsify/issues/273, let's make sure the build task runs to cover most build situations (particularly look into running `gulp pl:scss-to-yaml` and `gulp pl:full`).

**Comment by BrizzleRocker** [comment]
`gulp pl:full` includes `pl:scss-to-yaml` so I suspect that all that might be needed is a change to line 157:

`gulp.task('build', ['imagemin', 'scripts', 'styleguide-scripts', 'css', 'icons', 'pl:full']);`

**Comment by evanmwillhite** [comment]
Truth ☝️ 

Also, we talked about this in a practice group today and should probably be this: 

`gulp.task('build', ['compile', 'scripts', 'css']);`
